name: Compilação e Verificação do Angular

on:
  push:
    branches:
      - main
      - 'G*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código
        uses: actions/checkout@v2

      - name: Configurar o Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Instalar dependências
        run: npm install

      - name: Executar Verificação Angular
        run: ng lint

      - name: Verificar código não utilizado
        run: tslint --project tsconfig.json --format stylish --force
